<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>liquidsoap</string>
    <key>fileTypes</key>
    <array>
      <string>liq</string>
    </array>
    <key>scopeName</key>
    <string>source.liquidsoap</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bindings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expressions</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.other.liquidsoap</string>
            <key>match</key>
            <string>(%ifdef|%ifndef|%ifversion|%ifnversion|%ifencoder|%ifnencoder|%else|%endif)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.function.declaration.liquidsoap</string>
            <key>match</key>
            <string>-&gt;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.boolean.liquidsoap</string>
            <key>match</key>
            <string>\b(and|or|not)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.spread.liquidsoap</string>
            <key>match</key>
            <string>\.\.\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.append.liquidsoap</string>
            <key>match</key>
            <string>::</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.liquidsoap</string>
            <key>match</key>
            <string>[+\-/*]\.?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.compare.liquidsoap</string>
            <key>match</key>
            <string>(&gt;=|&lt;=|&gt;|&lt;|==|!=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.set.liquidsoap</string>
            <key>match</key>
            <string>:=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.coalesce.liquidsoap</string>
            <key>match</key>
            <string>\?\?</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>comma separator</string>
            <key>name</key>
            <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
            <key>match</key>
            <string>,</string>
          </dict>
        </array>
      </dict>
      <key>bindings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>for loop</string>
            <key>match</key>
            <string>\b(for)[[:space:]]+(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.binding.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>let expression binding</string>
            <key>match</key>
            <string>\b(let)[[:space:]]+(eval[[:space:]]+|replaces[[:space:]]+|json\.parse(?:\[[^\]]*\])?[[:space:]]+|yaml\.parse(?:\[[^\]]*\])?[[:space:]]+)?(?&lt;!eval|replaces|json\.parse|yaml\.parse)(__*|_*[[:alpha:]][[[:alpha:]]0-9_'.]*)[[:space:]]*(?!,|::|[[:space:]])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.declaration.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.liquidsoap</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.binding.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>list pattern binding</string>
            <key>begin</key>
            <string>\b(let)[[:space:]]+\[</string>
            <key>end</key>
            <string>\]</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.declaration.pattern.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pattern-assignments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>module pattern binding</string>
            <key>begin</key>
            <string>\b(let)[[:space:]]+\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.declaration.pattern.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pattern-assignments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>tuple pattern binding</string>
            <key>begin</key>
            <string>\b(let)[[:space:]]+\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.declaration.pattern.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pattern-assignments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>def expression binding with params</string>
            <key>begin</key>
            <string>\b(def)[[:space:]]+(rec[[:space:]]+|replaces[[:space:]]+)?(?&lt;!rec|replaces)(__*|_*[[:alpha:]][[[:alpha:]]0-9_'.]*)</string>
            <key>end</key>
            <string>(?&lt;=end)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.definition.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.liquidsoap</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.binding.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.end.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#def-params</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function-body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>expression binding</string>
            <key>match</key>
            <string>\b(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)[[:space:]]*=(?!=)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.binding.liquidsoap</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>inline if</string>
            <key>begin</key>
            <string>(\?)(?![\?\.])</string>
            <key>end</key>
            <string>(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>if</string>
            <key>begin</key>
            <string>\b(if)\b</string>
            <key>end</key>
            <string>\b(end)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(then|else|elsif)\b</string>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>for</string>
            <key>begin</key>
            <string>\b(for)\b</string>
            <key>end</key>
            <string>\b(end)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(to|do)\b</string>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>while</string>
            <key>begin</key>
            <string>\b(while)\b</string>
            <key>end</key>
            <string>\b(end)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(do)\b</string>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>try</string>
            <key>begin</key>
            <string>\b(try)\b</string>
            <key>end</key>
            <string>\b(end)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(catch)[[:space:]]+(__*|[[:alpha:]][[[:alpha:]]0-9_']*)[[:space:]]+(do)\b</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.liquidsoap</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.binding.liquidsoap</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.liquidsoap</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>begin</key>
                <string>\b(catch)[[:space:]]+(__*|[[:alpha:]][[[:alpha:]]0-9_']*)[[:space:]]+(:)</string>
                <key>end</key>
                <string>(do)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.liquidsoap</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.binding.liquidsoap</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.liquidsoap</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.liquidsoap</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#expressions</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>begin</string>
            <key>begin</key>
            <string>\b(begin)\b</string>
            <key>end</key>
            <string>\b(end)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>record declaration</string>
            <key>begin</key>
            <string>\.?\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#records</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>fun with params</string>
            <key>begin</key>
            <string>\b(fun)[[:space:]]*\(</string>
            <key>end</key>
            <string>\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.definition.anonymous.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#def-param</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>function invocation</string>
            <key>name</key>
            <string>meta.function-call.liquidsoap</string>
            <key>begin</key>
            <string>\??\.?%?(__*|[[:alpha:]][[[:alpha:]]0-9_']*)[[:space:]]*\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#function-call-arguments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>method invocation</string>
            <key>match</key>
            <string>(\??\.)(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.method.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)(?![=:])</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.type-annotation.liquidsoap</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.cast.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(int|float|unit|bool)(?:(\?)|\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ground.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(source)\(</string>
            <key>end</key>
            <string>\)(\??)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.source.liquidsoap</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#source-type-arguments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>source(\??)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.source.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)(\??)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>comma separator</string>
                <key>name</key>
                <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
                <key>match</key>
                <string>,</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>list</string>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\](\??)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>comma separator</string>
                <key>name</key>
                <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
                <key>match</key>
                <string>,</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>record</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}(\??)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>method assignment</string>
                <key>match</key>
                <string>\b(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)[[:space:]]*:(?!:)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.method.liquidsoap</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>comma separator</string>
                <key>name</key>
                <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
                <key>match</key>
                <string>,</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>source-type-arguments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([[[:alpha:]]]+)(\??)[[:space:]]*=[[:space:]]*([[[:alpha:]].]+)(\([[[:alpha:]]0-9.]+\))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.source.track.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.type.source.format.liquidsoap</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.type.source.format.params.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([[[:alpha:]]]+)(\??)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.source.track.liquidsoap</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>comma separator</string>
            <key>name</key>
            <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
            <key>match</key>
            <string>,</string>
          </dict>
        </array>
      </dict>
      <key>function-call-arguments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)=</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.language.arguments.named.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>comma separator</string>
            <key>name</key>
            <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9][0-9_]*?)\.[0-9][0-9_]*(?!\})\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.float.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0(x|X)[0-9][0-9a-fA-F_]+\b</string>
            <key>name</key>
            <string>constant.numeric.hexadecimal.integer.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0(o|O)[0-9][0-9_]+\b</string>
            <key>name</key>
            <string>constant.numeric.octal.integer.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+w?)[0-9]+h[0-9]+\b</string>
            <key>name</key>
            <string>constant.time.predicate.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[0-9]+w([0-9]+h?)([0-9]+m?)([0-9]+s?)\b</string>
            <key>name</key>
            <string>constant.time.predicate.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+w?)[0-9]+h([0-9]+m?)([0-9]+s?)\b</string>
            <key>name</key>
            <string>constant.time.predicate.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+w?)([0-9]+h?)[0-9]+m([0-9]+s?)\b</string>
            <key>name</key>
            <string>constant.time.predicate.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+w?)([0-9]+h?)([0-9]+m?)[0-9]+s\b</string>
            <key>name</key>
            <string>constant.time.predicate.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[0-9][0-9_]*\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.integer.liquidsoap</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>#&lt;</string>
            <key>end</key>
            <string>&gt;#</string>
            <key>name</key>
            <string>comment.block.liquidsoap</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments-doc</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>#</string>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.number-sign.liquidsoap</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments-doc</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments-doc</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>@param</string>
            <key>name</key>
            <string>comment.doc.param.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>@category</string>
            <key>name</key>
            <string>comment.doc.category.liquidsoap</string>
          </dict>
          <dict>
            <key>match</key>
            <string>@argsof</string>
            <key>name</key>
            <string>comment.doc.argsof.liquidsoap</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.liquidsoap</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-escapes</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.liquidsoap</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-escapes</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>r/</string>
            <key>end</key>
            <string>/[gismu]*</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.liquidsoap</string>
                <key>match</key>
                <string>\\/</string>
              </dict>
            </array>
            <key>name</key>
            <string>string.regexp.liquidsoap</string>
          </dict>
        </array>
      </dict>
      <key>string-escapes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.liquidsoap</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>string.interpolation.liquidsoap</string>
            <key>begin</key>
            <string>#\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>string.interpolation.escape.liquidsoap</string>
                <key>match</key>
                <string>\\}</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>identifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>encoder literal</string>
            <key>name</key>
            <string>variable.encoder.liquidsoap</string>
            <key>match</key>
            <string>%[[:alpha:]][[[:alpha:]]0-9_']*</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>variable literal</string>
            <key>name</key>
            <string>variable.liquidsoap</string>
            <key>match</key>
            <string>\b(?!r/)(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)</string>
          </dict>
        </array>
      </dict>
      <key>pattern-assignments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>variable assignment</string>
            <key>name</key>
            <string>entity.name.function.binding.liquidsoap</string>
            <key>match</key>
            <string>\b(?!r/)(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>list pattern</string>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pattern-assignments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>tuple pattern</string>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pattern-assignments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>module pattern</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pattern-assignments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>comma separator</string>
            <key>name</key>
            <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.spread.liquidsoap</string>
            <key>match</key>
            <string>\.\.\.</string>
          </dict>
        </array>
      </dict>
      <key>records</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>method assignment</string>
            <key>match</key>
            <string>\b(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)[[:space:]]*=(?!=)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.method.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>comma separator</string>
            <key>name</key>
            <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>def-param</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>~(__*|_*[[:alpha:]][[[:alpha:]]0-9_']*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.liquidsoap</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>comma separator</string>
            <key>name</key>
            <string>keyword.other.liquidsoap punctuation.comma punctuation.separator.comma</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>def-params</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>[[:space:]]*\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#def-param</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>[[:space:]]*(?:=|\n)</string>
            <key>end</key>
            <string>\b(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.end.liquidsoap</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>